<?php
/*
    IP-Biter: The Hacker-friendly Tracking Framework
    Copyright (C) 2017  Damiano Falcioni (damiano.falcioni@gmail.com)
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.
    
    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>. 
    
    -------------------------------------------------------------------------
    
README.md

# IP-Biter - Framework
#### The Hacker-friendly Tracking Framework
IP-Biter is an open source, easy to deploy, tracking framework that generate high configurables and uniques tracking images and links 
to embed in e-mails, sites or chat systems and visualize, in an hacker-friendly dashboard, high detailed reports of the tracked users 
who visualize the image or open the links.

## Features
- Very high configurable tracking image generation
- Tracking links generation
- Tracking hided and not recognizable from the target point of view
- Integrated Dashboard
- Self-tracking prevention
- Possibility to stop and start the tracking at any time
- Possibility to hide the Dashboard and protect its access with a password
- Live tracking reports from the Dashboard
- Tracking reports live delivered to a configurable mail address
- Different IP analysis services
- User-Agent analysis service
- Integrate URL shortening service
- AllInOne PHP file
- No need for a Database
- Open Source

...and many many more!

Give it a try!

## Getting Started
#### Access the Dashboard
1) Access the dashboard through ipb.php?op=$dashboardPage (or through ipb.php if $dashboardPage=='')
    - If $dashboardPageSecret!='' then a login page will appear asking for the $dashboardPageSecret value  
#### Create a new configuration
2) When the dashboard is opened without parameters, a new configuration is created
    - Another empty new configuration can be generate clicking the "New" button
3) Configure the tracking image and the advanced setting if needed
    - It is possible to left the original image url empty. In this case an empty image will be used.
4) Add tracking links if needed
    - It is possible to left the original link empty. In this case the link will generate a 404 page.
5) Save the configuration
6) Distribute the generated image or the links to start the tracking
    - You can click the copy button and paste in a html rich email editor like gmail
    - NOTE: If you try to open the generated image or links but have in the same browser the dashboard page opened and loaded, your request will not be tracked (self-tracking prevention feature)
    
#### Load an existing configuration
7) When the dashboard is opened with the parameter "uuid", the associated configuration is loaded
    - Another configuration can be loaded pasting the "Track UUID" in the dashboard relative field and clicking the "Load" button
8) The reports will be automatically visualized in the "Tracking Reports" section of the dashboard

## Security Notes
- Change the folders name and the dashboard page in the configuration section in order to improve the security
- Add the following lines to the .htaccess file in order to deny the access to the "configs" and "reports" folders:
```
DirectoryIndex ipb.php
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^(configs/|reports/) - [F]
</IfModule>
```

## Live DEMO
<!-- 
Hi and welcome to a tracking link live demonstration. 
The one below is a autogenerated link that redirect to https://ipbiter.000webhostapp.com/?op=dashboard (the demo page) and in the meanwhile, will track you :P
From this url you are not able to access the relative dashboard. 
Did not trust me?
Try to hack it as a challange and report me your success; you will be rewarded with a coffee <3
-->
Have a look at the [DEMO](http://ipbiter.000webhostapp.com/?op=l&tid=9fae1fc1-a4dd-44f1-bbaa-0cede56d3cdc&lid=5ab6bbdb-8f7c-45ea-9f33-18d0db7cfd79) (notifications limited at 50 mail/day and 1h/day downtime expected)

## Support Me <3
<!--
Hi and welcome again to a tracking image live demonstration. 
The one below is a autogenerated link that show this image: https://user-images.githubusercontent.com/8982949/33011169-6da4af5e-cddd-11e7-94e5-a52d776b94ba.png
when your browser loaded this image, you was been tracked :)
From this url you are not able to access the relative dashboard. 
Did not trust me?
Try to hack it as a challange and report me your success; you will be rewarded with another coffee <3
-->
[![Buy me a coffee](http://ipbiter.000webhostapp.com/?op=i&tid=9fae1fc1-a4dd-44f1-bbaa-0cede56d3cdc)](https://www.paypal.me/damianofalcioni/0.99)

*/

/*START CONFIGURATION SECTION*/
$dashboardPage = 'dashboard';
$dashboardPageSecret = '';
$configFolder = 'configs';
$reportFolder = 'reports';
$errorLogFile = 'error.log';
/*END CONFIGURATION SECTION*/

$logError = function($message) use ($errorLogFile){
    file_put_contents(getcwd().'/'.$errorLogFile, date('d/m/Y H:i:s', time()).' '.$_SERVER['REMOTE_ADDR'].' '.$message."\r\n", FILE_APPEND);
};

if(
    ((!isset($_REQUEST['op']) && $dashboardPage == '') || (isset($_REQUEST['op']) && $_REQUEST['op'] == $dashboardPage)) &&
    ((!isset($_REQUEST['secret']) && $dashboardPageSecret == '') || (isset($_REQUEST['secret']) && $_REQUEST['secret'] == $dashboardPageSecret))
){
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>IP-Biter Dashboard</title>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="https://bootswatch.com/3/darkly/bootstrap.min.css">-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript">
var Dashboard = {
  documentTitle : 'IP-Biter Dashboard',
  _dashboardSecret : '<?php echo isset($_REQUEST['secret'])?$_REQUEST['secret']:'';?>',
  _anonymRedirectService : 'https://anon.to/?',
  _imageCustomHeaderIds : {},
  _trackingLinksIds : {},
  _trackTimestamp : 0,
  _backgroudTrackListUpdateId : 0,
  _backgroudTrackListUpdateIntervallInSeconds : 10,
  _isFocused : true,
  
  trackingUUID : '',

  services : {
      callUrlShortnerService : function(url, successCallback, failureCallback){
          Utils.callService('shortening', 'url='+encodeURIComponent(url), null, function(data){
              successCallback(data.shortenedUrl);
          }, failureCallback);
      },
      callConfigSaverService : function(configJson, successCallback, failureCallback){
          Utils.callService('save', null, configJson, successCallback, failureCallback);
      },
      callLoadConfigService : function(uuid, successCallback, failureCallback){
          Utils.callService('loadConfig', 'id='+uuid, null, function(data){
              successCallback(data.config);
          }, failureCallback);
      },
      callLoadTrackingReportService : function(uuid, successCallback, failureCallback){
          Utils.callService('loadTrack', 'id='+uuid, null, function(data){
              successCallback(data.track);
          }, failureCallback);
      },
      callPingTrackService : function(uuid, time, successCallback, failureCallback){
          Utils.callService('ping', 'id='+uuid+'&time='+time+'&rnd='+Utils.generateUUID(), null, function(data){
              successCallback(data.valid);
          }, failureCallback);
      }
  },
  
  loadUUID : function(){
      var uuid = $('#trackUUIDTxt').val();
      Dashboard.cleanAll();
      $('#trackUUIDTxt').val(uuid);
      $('#configurationDiv').collapse('hide');
      $('#reportsDiv').collapse('show');
      
      Dashboard.services.callLoadConfigService(uuid, function(configJson){
          Dashboard.setCookie();
          Dashboard.trackingUUID = configJson.trackUUID;
          $('#trackingEnabledChk').prop('checked', configJson.trackingEnabled);
          $('#mailIdTxt').val(configJson.mailId);
          $('#notificationMailTxt').val(configJson.notificationAddress);
          $('#trackingImageOriginalUrlTxt').val(configJson.trackingImage).trigger('change');
          $('#trackingImageHTTPStatusTxt').val(configJson.trackingImageStatusCode);
          configJson.trackingImageCustomHeaderList.forEach(function(item){
              Dashboard.addCustomHTTPHeader(item);
          });
          $('#trackingImgUrlTxt').val(configJson.trackingImageGeneratedUrl);
          $('#trackingImgShortUrlTxt').val(configJson.trackingImageShortUrl);
          for(var linkId in configJson.trackingLinks)
              Dashboard.addTrackingLink(linkId, configJson.trackingLinks[linkId].original, configJson.trackingLinks[linkId].generated, configJson.trackingLinks[linkId].shortened);
          
          Dashboard.loadTrackingReports();
      }, function(error){
          Utils.showError(error, $('#trackUUIDMsgs'));
      });
  },
  
  newUUID : function(){
      Dashboard.cleanAll();
      Dashboard.addDefaultHTTPHeader();
      Dashboard.trackingUUID = Utils.generateUUID();
      
      $('#trackUUIDTxt').val(Utils.generateUUID());
      
      $('#configurationDiv').collapse('show');
      $('#reportsDiv').collapse('hide');
      
      var imageLink = Dashboard.generateTrackingImageUrl();
      $('#trackingImgUrlTxt').val(imageLink);
      
      Dashboard.services.callUrlShortnerService(imageLink, function(shortUrl){
          $('#trackingImgShortUrlTxt').val(shortUrl);
      }, function(error){
          $('#trackingImgShortUrlTxt').val('');
          Utils.showError(error, $('#trackingImageConfigDiv'));
      });
  },
  
  saveConfiguration : function(){
      var configJson = Dashboard.generateConfigJson();
      Dashboard.services.callConfigSaverService(configJson, function(successData){
          Dashboard.setCookie();
          Utils.showSuccess('Configuration Saved', $('#saveConfigMsgs'));
          Dashboard.loadTrackingReports();
          if(Utils.getURLParameter('uuid') != configJson.uuid)
              setTimeout(function(){
                  $('<form method="post" action="'+Utils.getCurrentPath()+'?uuid='+configJson.uuid+(Utils.getURLParameter('op')!=''?'&op='+Utils.getURLParameter('op'):'')+'"><input name="secret" type="hidden" value="'+Dashboard._dashboardSecret+'"></form>').appendTo($('body')).submit().remove();
              }, 1000);
      },function(error){
          Utils.showError(error, $('#saveConfigMsgs'));
      });
  },
  
  loadTrackingReports : function(update){
      Dashboard.services.callLoadTrackingReportService($('#trackUUIDTxt').val(), function(trackingReportJson){
          Dashboard._trackTimestamp = trackingReportJson.time;
          
          if(!update)
              $('#reportsDiv').empty();
          
          var _generateAnalyzeIPButtons = function(ip){
              var ipAnalyzeServiceList = [{
                  name : 'shodan.io',
                  url : 'https://www.shodan.io/search?query='+ip
              }, {
                  name : 'centralops.net',
                  url : 'https://centralops.net/co/DomainDossier.aspx?addr='+ip+'&dom_whois=true&dom_dns=true&traceroute=true&net_whois=true&svc_scan=true'
              }, {
                  name : 'udger.com',
                  url : 'https://udger.com/resources/online-parser?action=analyze&Fip='+ip
              }, {
                  name : 'dnsstuff.com whois',
                  url : 'http://www.dnsstuff.com/tools#whois|type=ipv4&&value='+ip
              }, {
                  name : 'ip-tracker.org',
                  url : 'http://www.ip-tracker.org/locator/ip-lookup.php?ip='+ip
              }, {
                  name : 'infobyip.com',
                  url : 'https://www.infobyip.com/ip-'+ip+'.html'
              }, {
                  name : 'infobyip.com whois',
                  url : 'https://www.infobyip.com/ipwhois-'+ip+'.html'
              }, {
                  name : 'ipinfo.io', //json https://ipinfo.io/8.8.8.8/json
                  url : 'https://ipinfo.io/'+ip
              }, {
                  name : 'ipapi.co', //json https://ipapi.co/8.8.8.8/json/
                  url : 'https://ipapi.co/'+ip
              }];
              //http://freegeoip.net/json/83.65.190.82 e integrare mappa https://stackoverflow.com/questions/17290256/get-google-map-link-with-latitude-longitude
              
              var list = '';
              ipAnalyzeServiceList.forEach(function(ipAnalyzeService){
                  list += '<li class="link"><a href="'+Dashboard._anonymRedirectService+ipAnalyzeService.url+'" target="_blank">'+ipAnalyzeService.name+'</a></li>';
              });
              
              return '<div class="input-group-btn dropdown"><button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Analyze <span class="caret"></span></button><ul class="dropdown-menu">'+list+'</ul></div>';
          };
          
          var _generateAnalyzeAgentButton = function(userAgent){
              var link = 'https://udger.com/resources/online-parser?action=analyzev&Fuas='+encodeURIComponent(userAgent);
              return '<a class="btn btn-default" role="button" href="'+Dashboard._anonymRedirectService+link+'" target="_blank">Analyze</a>';
          };
          
          var newTracksCounter = 0;
          trackingReportJson.trackList.forEach(function(track, trackIndex){
              if(trackIndex < $('#reportsDiv').children().length)
                  return;
              newTracksCounter++;
              
              if(!Dashboard._isFocused && newTracksCounter!=0)
                  document.title = '('+newTracksCounter+') '+Dashboard.documentTitle;
              
              var domId = Utils.generateUUID();
              $('#reportsDiv').prepend(
                  $('<div class="list-group-item">').append(
                      $('<div class="row link" title="Click for details">').append(
                          $('<div class="col-lg-2">').append(
                              '<h4><span class="label label-default">'+track.time+'</span></h4>'
                          )
                      ).append(
                          $('<div class="col-lg-4">').append(
                              $('<div class="input-group">').append(
                                  '<span class="input-group-addon">Remote IP: </span>'
                              ).append(
                                  $('<input type="text" class="form-control" value="'+track.ip+'" readonly>').click(function(e){
                                      $(this).select();
                                      document.execCommand("copy");
                                  })
                              ).append(
                                  _generateAnalyzeIPButtons(track.ip)
                              )
                          )
                      ).click(function(e){
                          if (e.target.tagName != 'BUTTON' && e.target.tagName != 'A' && e.target.tagName != 'INPUT')
                              $('#'+domId+'_headers_div').toggle();
                      })
                  ).append(
                      $('<div class="row" id="'+domId+'_headers_div" style="display:none;">').append(
                          $('<div class="col-lg-12">').append(
                              $('<table class="table table-condensed">').append(
                                  $('<tbody>').append(function(){
                                      var ret = [];
                                      ret.push('<tr><th style="vertical-align:middle; white-space:nowrap; width:1%;">Header Fields</th><th style="vertical-align:middle; white-space:nowrap; width:1%;"></th><th></th></tr>');
                                      for(var header in track.headers){
                                          var analysisButton = null;
                                          var headerLowCase = header.toLowerCase();
                                          if(headerLowCase == 'user-agent')
                                              analysisButton = _generateAnalyzeAgentButton(track.headers[header]);
                                          if(headerLowCase == 'x-forwarded-for')
                                              analysisButton = _generateAnalyzeIPButtons(track.headers[header].split(',')[0]);
                                          if(headerLowCase == 'x-real-ip')
                                              analysisButton = _generateAnalyzeIPButtons(track.headers[header]);
                                          ret.push('<tr><td style="vertical-align:middle; white-space:nowrap;">'+header+'</td><td style="vertical-align:middle; white-space:nowrap;">'+(analysisButton!=null?analysisButton:'')+'</td><td style="vertical-align:middle;">'+track.headers[header]+'</td></tr>');
                                      }
                                      return ret;
                                  }())
                              )
                          )
                      )
                  ).hide().fadeIn(500)
              );
          });
      
      }, function(error){
          Utils.showError(error, $('#reportsTable'));
      });
  },
  
  generateTrackingImageUrl : function(){
      return Utils.getHost()+Utils.getCurrentPath()+'?op=i&tid='+Dashboard.trackingUUID;
  },
  
  generateTrackingLinkUrl : function(linkUrl){
      return Utils.getHost()+Utils.getCurrentPath()+'?op=l&tid='+Dashboard.trackingUUID+'&lid='+linkUrl;
  },
  
  addCustomHTTPHeader : function(value){
      var domId = Utils.generateUUID();
      Dashboard._imageCustomHeaderIds[domId]=1;
      
      $('#customHTTPHeaderTable').append(
          $('<tr id="'+domId+'_tr">').append(
              $('<td>').append(
                  $('<div class="input-group">').append(
                      $('<input id="header_'+domId+'_txt" type="text" class="form-control" placeholder="Add custom header here">').val(value)
                  ).append(
                      $('<div class="input-group-addon link" style="font-size:20px;font-weight:700;">&times;</div>').click(function(){
                          $('#'+domId+'_tr').remove();
                          delete Dashboard._imageCustomHeaderIds[domId];
                      })
                  )
              )
          )
      );
  },
  
  addDefaultHTTPHeader : function(){
      Dashboard.addCustomHTTPHeader('Content-Type: image/png');
      Dashboard.addCustomHTTPHeader('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
      Dashboard.addCustomHTTPHeader('Cache-Control: post-check=0, pre-check=0');
      Dashboard.addCustomHTTPHeader('Pragma: no-cache');
      Dashboard.addCustomHTTPHeader('Expires: 0');
      Dashboard.addCustomHTTPHeader('P3P: CP="OTI DSP COR CUR IVD CONi OTPi OUR IND UNI STA PRE"');
  },
  
  addTrackingLink :function(linkUUID, originalUrl, generatedUrl, shortUrl){
      var linkId = linkUUID!=null?linkUUID:Utils.generateUUID();
      Dashboard._trackingLinksIds[linkId]=1;
      var trackingLink = generatedUrl!=null?generatedUrl:Dashboard.generateTrackingLinkUrl(linkId);
      
      $('#trackingLinksTable').append(
          $('<tr id="'+linkId+'_tr">').append(
              $('<td>').append(
                  $('<div class="input-group">').append(
                      $('<input id="link_'+linkId+'_original_txt" type="text" class="form-control" placeholder="Add the original URL here">')
                  ).append(
                      '<span class="input-group-addon">Tracking Link Generated URL:</span>'
                  ).append(
                      $('<input id="link_'+linkId+'_generated_txt" type="text" class="form-control" placeholder="Auto-generated Tracking Link" readonly>').click(function(){
                          $('#link_'+linkId+'_generated_txt').select();
                          document.execCommand("copy");
                      })
                  ).append(
                      $('<span class="input-group-addon link" title="Copy to clipboard"><span class="glyphicon glyphicon-copy"></span></span>').click(function(){
                          $('#link_'+linkId+'_generated_txt').select();
                          document.execCommand("copy");
                      })
                  ).append(
                      $('<input id="link_'+linkId+'_short_txt" type="text" class="form-control" placeholder="Auto-generated Shortened Tracking Link" readonly>').click(function(){
                          $('#link_'+linkId+'_short_txt').select();
                          document.execCommand("copy");
                      })
                  ).append(
                      $('<span class="input-group-addon link" title="Copy to clipboard"><span class="glyphicon glyphicon-copy"></span></span>').click(function(){
                          $('#link_'+linkId+'_short_txt').select();
                          document.execCommand("copy");
                      })
                  ).append(
                      $('<div class="input-group-addon link" style="font-size:20px;font-weight:700;">&times;</div>').click(function(){
                          $('#'+linkId+'_tr').remove();
                          delete Dashboard._trackingLinksIds[linkId];
                      })
                  )
              )
          )
      );
      
      $('#link_'+linkId+'_original_txt').val(originalUrl);
      $('#link_'+linkId+'_generated_txt').val(trackingLink);
      
      if(shortUrl!=null)
          $('#link_'+linkId+'_short_txt').val(shortUrl);
      else{
          Dashboard.services.callUrlShortnerService(trackingLink, function(shortUrl){
              $('#link_'+linkId+'_short_txt').val(shortUrl);
          }, function(error){
              $('#link_'+linkId+'_short_txt').val('');
              Utils.showError(error, $('#trackingLinksTable'));
          });
      }
  },
  
  generateConfigJson : function(){
      return {
          uuid : $('#trackUUIDTxt').val(),
          trackUUID : Dashboard.trackingUUID,
          trackingEnabled : $('#trackingEnabledChk').is(':checked'),
          mailId : $('#mailIdTxt').val(),
          notificationAddress : $('#notificationMailTxt').val(),
          trackingImage : $('#trackingImageOriginalUrlTxt').val(),
          trackingImageStatusCode : parseInt($('#trackingImageHTTPStatusTxt').val()),
          trackingImageCustomHeaderList : function(){
              var ret = [];
              for(var id in Dashboard._imageCustomHeaderIds)
                  ret.push($('#header_'+id+'_txt').val());
              return ret;
          }(),
          trackingImageGeneratedUrl : $('#trackingImgUrlTxt').val(),
          trackingImageShortUrl : $('#trackingImgShortUrlTxt').val(),
          trackingLinks : function(){
              var ret = {};
              for(var id in Dashboard._trackingLinksIds)
                  ret[id] = {
                      original : $('#link_'+id+'_original_txt').val(),
                      generated : $('#link_'+id+'_generated_txt').val(),
                      shortened : $('#link_'+id+'_short_txt').val()
                  };
              return ret;
          }()
      };
  },
  
  startBackgroundTrackListUpdate : function(){
      var _updateFunction = function(){
          if(Dashboard.trackingUUID == '' || Dashboard._trackTimestamp == 0){
              if(Dashboard._backgroudTrackListUpdateIntervallInSeconds != 0)
                  Dashboard._backgroudTrackListUpdateId = setTimeout(_updateFunction, Math.round(Dashboard._backgroudTrackListUpdateIntervallInSeconds)*1000);
              return;
          }
          
          Dashboard.services.callPingTrackService(Dashboard.trackingUUID, Dashboard._trackTimestamp, function(isValid){
              if(isValid===false)
                  Dashboard.loadTrackingReports(true);
              if(Dashboard._backgroudTrackListUpdateIntervallInSeconds != 0)
                  Dashboard._backgroudTrackListUpdateId = setTimeout(_updateFunction, Math.round(Dashboard._backgroudTrackListUpdateIntervallInSeconds)*1000);
          }, function(error){
              console.log(error);
              //Utils.showError(error, $('#trackReportMsgs'));
              //Dashboard.stopBackgroundTrackListUpdate();
              if(Dashboard._backgroudTrackListUpdateIntervallInSeconds != 0)
                  Dashboard._backgroudTrackListUpdateId = setTimeout(_updateFunction, Math.round(Dashboard._backgroudTrackListUpdateIntervallInSeconds)*1000);
          });
          
      };
      _updateFunction();
  },
  
  stopBackgroundTrackListUpdate : function(){
      clearTimeout(Dashboard._backgroudTrackListUpdateId);
  },
  
  cleanAll : function(){
      $('#trackUUIDTxt').val('');
      Dashboard.trackingUUID='';
      Dashboard._trackTimestamp = 0;
      $('trackingEnabledChk').prop('checked', true);
      $('#mailIdTxt').val('');
      $('#notificationMailTxt').val('');
      $('#trackingImageOriginalUrlTxt').val('').trigger('change');
      $('#trackingImageHTTPStatusTxt').val('200');
      $('#customHTTPHeaderTable').empty();
      Dashboard._imageCustomHeaderIds = {};
      $('#trackingImgUrlTxt').val('');
      $('#trackingImgShortUrlTxt').val('');
      $('#trackingLinksTable').empty();
      Dashboard._trackingLinksIds = {};
      $('#reportsDiv').empty();
  },
  
  setCookie : function(){
      document.cookie = $('#trackUUIDTxt').val()+"=1";
  },
  
  initialize : function(){
      $('#uuidLoadBtn').click(function(){
          Dashboard.loadUUID();
      });
      $('#uuidNewBtn').click(function(){
          Dashboard.newUUID();
      });
      $('#trackUUIDCopyBtn').click(function(){
          $('#trackUUIDTxt').select();
          document.execCommand("copy");
      });
      $('#trackingImageOriginalUrlTxt').change(function(){
          $('#trackingImageImg').attr('src', $('#trackingImageOriginalUrlTxt').val());
      });
      $('#trackingImgUrlCopyBtn').click(function(){
          Utils.copyToClipboard('<img src="'+$('#trackingImgUrlTxt').val()+'"/>');
      });
      $('#trackingImgUrlTxt').click(function(){
          $('#trackingImgUrlTxt').select();
          document.execCommand("copy");
      });
      $('#trackingImgShortUrlCopyBtn').click(function(){
          Utils.copyToClipboard('<img src="'+$('#trackingImgShortUrlTxt').val()+'"/>');
      });
      $('#trackingImgShortUrlTxt').click(function(){
          $('#trackingImgShortUrlTxt').select();
          document.execCommand("copy");
      });
      $('#addCustomHTTPHeaderBtn').click(function(){
          Dashboard.addCustomHTTPHeader();
      });
      $('#trackingImageEmoji1Btn').click(function(){
          $('#trackingImageOriginalUrlTxt').val('https://www.facebook.com/images/emoji.php/v9/z6/1/32/1f642.png').trigger('change');
      });
      $('#trackingImageUploadBtn').click(function(e){
          e.preventDefault();
          $("#trackingImageFileInput").trigger('click');
      });
      $('#trackingImageFileInput').change(function(e){
          Utils.readFileAsDataURL(e.target.files[0], function(content){
              $('#trackingImageOriginalUrlTxt').val(content).trigger('change');
          }); 
      });
      $('#addTrackingLinkBtn').click(function(){
          Dashboard.addTrackingLink();
      });
      $('#saveConfigBtn').click(function(){
          Dashboard.saveConfiguration();
      });
      
      var uuidParam = Utils.getURLParameter('uuid');
      if(uuidParam!=null && uuidParam!=''){
          $('#trackUUIDTxt').val(uuidParam);
          $('#uuidLoadBtn').trigger('click');
      } else {
          Dashboard.newUUID();
      }
      
      Dashboard.startBackgroundTrackListUpdate();
      
      $(window).focus(function(){
          document.title = Dashboard.documentTitle;
          Dashboard._isFocused = true;
      }).blur(function(){
          Dashboard._isFocused = false;
      });

  }
};

var Utils = {
  showError : function(error, parentDom){
      console.log(error);
      $('<div class="alert alert-danger fade in" role="alert"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>Error occurred:<br>'+error+'</div>')
          .fadeTo(5000, 500)
          .appendTo((parentDom!=null)?parentDom:$('#mainContainer'));
  },
  
  showSuccess : function(info, parentDom){
      console.log(info);
      $('<div class="alert alert-success fade in" role="alert"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'+info+'</div>')
          .fadeTo(5000, 500)
          .slideUp(500, function(){
              $(this).remove();
          })
          .appendTo((parentDom!=null)?parentDom:$('#mainContainer'));
  },
  
  generateUUID : function() {
      var d = new Date().getTime();
      if (typeof performance !== 'undefined' && typeof performance.now === 'function')
          d += performance.now(); //use high-precision timer if available
      
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
          var r = (d + Math.random() * 16) % 16 | 0;
          d = Math.floor(d / 16);
          return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
      });
  },
  
  copyToClipboard : function(text){
      if(window.clipboardData != null){ //IE
          window.clipboardData.setData('text', text);
      } else {
          var listener = function(e) {
              var clipboard = e.clipboardData || e.originalEvent.clipboardData;
              clipboard.setData('text/plain', text);
              clipboard.setData('text/html', text);
              clipboard.setData('text', text); //Edge
              e.preventDefault();
          }
          document.addEventListener('copy', listener);
          try{
            document.execCommand('copy');
          } finally {
            document.removeEventListener('copy', listener);
          }
      }
  },
  
  getURLParameter : function(sParam){
      var sPageURL = window.location.search.substring(1);
      var sURLVariables = sPageURL.split('&');
      for (var i = 0; i < sURLVariables.length; i++) {
          var sParameterName = sURLVariables[i].split('=');
          if (sParameterName[0] == sParam)
              return sParameterName[1];
      }
      return null;
  },
  
  getHost : function(){
      var ret = ((window.location.protocol == '')?'http:':window.location.protocol) + '//' + ((window.location.hostname == '')?'127.0.0.1':window.location.hostname) + ((window.location.port != '')?':'+window.location.port:'');        
      return ret;
  },
  
  getCurrentPath : function(){
      return window.location.pathname;
  },
  
  readFileAsDataURL : function(file, onLoadFunction){
      if(!file)
          return;
      if(!(window.File && window.FileReader && window.FileList && window.Blob)){
          alert('The File APIs are not fully supported in this browser.');
          return;
      }
      var reader = new FileReader();
      reader.onload = function(e) {
          var content = e.target.result;
          onLoadFunction(content);
      };
      reader.readAsDataURL(file);
  },
  
  callService : function(op, paramsQueryString, postData, successCallback, failureCallback){
      var serviceUrl = Utils.getCurrentPath()+'?op='+op+(paramsQueryString!=null?'&'+paramsQueryString:'');
      var ajaxConfig = {
          type: 'GET',
          url: serviceUrl,
          dataType : 'json',
          async: true,
          success : function(data, status){
              if(data.status==0)
                  successCallback(data);
              else
                  failureCallback('Internal error: ' + data.error);
          },
          error : function(request, status, error) {
              failureCallback('Error contacting the service: ' + serviceUrl + ' : ' + status + ' ' + error);
          }
      };
      
      if(postData!=null){
          ajaxConfig.type = 'POST';
          ajaxConfig.processData = false;
          ajaxConfig.contentType = 'application/json';
          ajaxConfig.data = JSON.stringify(postData);
      }
      
      $.ajax(ajaxConfig);
  }
};
    </script>
    <script type="text/javascript">
$(document).ready(Dashboard.initialize);
    </script>
    <style type="text/css">
@charset "UTF-8";
.slideThree {
    width: 150px;
    height: 26px;
    background: #eaeaea;
    position: relative;
    border-radius: 50px;
}
.slideThree:before {
    content: 'ENABLED';
    color: #00b503;
    position: absolute;
    left: 10px;
    z-index: 0;
    font: 12px/26px Arial, sans-serif;
    font-weight: bold;
}
.slideThree:after {
    content: 'DISABLED';
    color: #555;
    position: absolute;
    right: 10px;
    z-index: 0;
    font: 12px/26px Arial, sans-serif;
    font-weight: bold;
    text-shadow: 1px 1px 0px rgba(255, 255, 255, 0.15);
}
.slideThree input[type=checkbox] {
    visibility: hidden;
}
.slideThree input[type=checkbox]:checked + label {
    left: 74px;
}
.slideThree label {
    width: 73px;
    height: 20px;
    cursor: pointer;
    position: absolute;
    top: 3px;
    left: 3px;
    z-index: 1;
    background: ghostwhite;
    border-radius: 50px;
    transition: all 0.4s ease;
    box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.3);
}
.link{
    cursor: pointer;
    color: #428bca;
    white-space: nowrap;
}
.link:hover{
    color: #FFFFFF;
    background-color: #428bca;
}
    </style>
</head>
<body>
    <div id="mainContainer" class="container">
        <div class="page-header text-center">
            <h1>IP-Biter Framework </h1><h1><small>Dashboard</small></h1>
        </div>
        
        <div class="row form-group">
            <div class="col-lg-12">
                <div class="input-group">
                    <span class="input-group-addon">Track UUID</span>
                    <input id="trackUUIDTxt" type="text" class="form-control" placeholder="Unique track id">
                    <span id="trackUUIDCopyBtn" class="input-group-addon link" title="Copy to clipboard"><span class="glyphicon glyphicon-copy"></span></span>
                    <span class="input-group-btn">
                        <button id="uuidLoadBtn" class="btn btn-default" type="button">Load</button>
                        <button id="uuidNewBtn" class="btn btn-default" type="button">New</button>
                    </span>
                </div>
            </div>
        </div>
        <div id="trackUUIDMsgs"></div>
        
        <div class="panel panel-default">
            <div class="panel-heading link" data-toggle="collapse" data-target="#configurationDiv">
                <h4 class="panel-title">Tracking Configuration <span class="caret"></span></h4>
            </div>
            <div id="configurationDiv" class="panel-collapse collapse">
                <div class="panel-body">
                    
                    <div class="row form-group">
                        <div class="col-lg-2">
                            <p class="lead">Tracking status:</p>
                        </div>
                        <div class="col-lg-2">
                            <div class="slideThree">
                                <input id="trackingEnabledChk" type="checkbox" checked/>
                                <label for="trackingEnabledChk"></label>
                                 <!-- <div class="btn-group" data-toggle="buttons"><label class="btn btn-primary active"><input id="trackingEnabledChk" type="checkbox" autocomplete="off" checked/>Enabled</label></div>-->
                            </div>
                        </div>
                    </div>
                    
                    <div class="row form-group">
                        <div class="col-lg-12">
                            <div class="input-group">
                                <span class="input-group-addon">Description</span>
                                <input id="mailIdTxt" type="text" class="form-control" placeholder="E-mail Subject / Description">
                            </div>
                        </div>
                    </div>
                    
                    <div class="row form-group">
                        <div class="col-lg-12">
                            <div class="input-group">
                                <span class="input-group-addon">Notification address @</span>
                                <input id="notificationMailTxt" type="text" class="form-control" placeholder="E-mail where to receive notifications on new tracks">
                            </div>
                        </div>
                    </div>
                    
                    <div class="panel panel-default">
                        <div class="panel-heading"><h4 class="panel-title">Tracking Image</h4></div>
                        <div class="panel-body" id="trackingImageConfigDiv">
                            
                            <div class="row form-group">
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <span class="input-group-addon">Tracking Image to use</span>
                                        <input id="trackingImageOriginalUrlTxt" type="text" class="form-control" placeholder="Empty image. Provide an url or select one from the menu on the right">
                                        <div class="input-group-btn">
                                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Image selection <span class="caret"></span></button>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li><a href="#" id="trackingImageEmoji1Btn">Emoji :)</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#" id="trackingImageUploadBtn">Upload custom image</a><input id="trackingImageFileInput" type="file" accept="image/*" style="display: none;"></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-2">
                                    <div class="thumbnail">
                                        <div class="text-center"><b>Image Preview</b></div>
                                        <img id="trackingImageImg" src="">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="panel panel-default">
                                <div class="panel-heading link" data-toggle="collapse" data-target="#trackingImageAdvSettingDiv">
                                    <h4 class="panel-title">Tracking Image Advanced settings <span class="caret"></span></h4>
                                </div>
                                <div id="trackingImageAdvSettingDiv" class="panel-collapse collapse">
                                    <div class="panel-body">
                    
                                        <div class="row form-group">
                                            <div class="col-lg-4">
                                                <div class="input-group">
                                                    <span class="input-group-addon">Image HTTP response status code</span>
                                                    <input id="trackingImageHTTPStatusTxt" type="number" class="form-control" value="200">
                                                </div>
                                            </div>
                                        </div>
            
                                        <div class="row form-group">
                                            <div class="col-lg-2">
                                                <button id="addCustomHTTPHeaderBtn" class="btn btn-default" type="button">Add custom HTTP Header</button>
                                            </div>
                                        </div>
                                        <div class="row form-group">
                                            <div class="col-lg-12">
                                                <table class="table table-condensed table-hover">
                                                    <tbody id="customHTTPHeaderTable"></tbody>
                                                </table>
                                            </div>
                                        </div>
                    
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row form-group">
                                <div class="col-lg-12">
                                    <div class="input-group">
                                        <span class="input-group-addon">Tracking Image Generated URL:</span>
                                        <input id="trackingImgUrlTxt" type="text" class="form-control" placeholder="Auto-generated Image Tracking URL" readonly>
                                        <span id="trackingImgUrlCopyBtn" class="input-group-addon link" title="Copy to clipboard as HTML IMG Tag"><span class="glyphicon glyphicon-copy"></span></span>
                                        <input id="trackingImgShortUrlTxt" type="text" class="form-control" placeholder="Auto-generated Image Tracking Shortened URL" readonly>
                                        <span id="trackingImgShortUrlCopyBtn" class="input-group-addon link" title="Copy to clipboard as HTML IMG Tag"><span class="glyphicon glyphicon-copy"></span></span>
                                    </div>
                                </div>
                            </div>
            
                        </div>
                    </div>
                    
                    <div class="panel panel-default">
                        <div class="panel-heading"><h4 class="panel-title">Tracking Links</h4></div>
                        <div class="panel-body">
                            <div class="row form-group">
                                <div class="col-lg-2">
                                    <button id="addTrackingLinkBtn" class="btn btn-default" type="button">Create Tracking Link</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <table class="table table-condensed table-hover">
                                        <tbody id="trackingLinksTable"></tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row form-group">
                        <div class="col-lg-2">
                            <button id="saveConfigBtn" class="btn btn-default" type="button">Save</button>
                        </div>
                        <div class="col-lg-10" id="saveConfigMsgs"></div>
                    </div>

                </div>
            </div>
        </div>
         
        <div class="panel panel-default">
            <div class="panel-heading link" data-toggle="collapse" data-target="#reportsDiv">
                <h4 class="panel-title">Tracking Reports<span class="caret"></span></h4>
            </div>
            <div class="panel-collapse list-group" id="reportsDiv">
            </div>
            <div id="trackReportMsgs"></div>
        </div>

    </div>
</body>
</html>
<?php
    exit();
}

if(
    ((!isset($_REQUEST['op']) && $dashboardPage == '') || (isset($_REQUEST['op']) && $_REQUEST['op'] == $dashboardPage)) &&
    $dashboardPageSecret != '' &&
    (!isset($_REQUEST['secret']) || (isset($_REQUEST['secret']) && $_REQUEST['secret'] != $dashboardPageSecret))
){
?>
<html>
    <head>
        <style type="text/css">
            form{
                position: absolute;
                top: 50%;
                left: 50%;
                -moz-transform: translateX(-50%) translateY(-50%);
                -webkit-transform: translateX(-50%) translateY(-50%);
                transform: translateX(-50%) translateY(-50%);
            }
        </style>
    </head>
    <body>
        <form method="post">
            <input name="secret" type="password" autofocus>
            <input type="submit" value="OK">
        </form>
    </body>
</html>
<?php
    exit();
}

if(isset($_GET['op']) && $_GET['op'] == 'shortening'){
    header('Content-Type: application/json');
    try{
        if(!isset($_GET['url']))
            throw new Exception('url parameter required');
        $shortenedUrl = @file_get_contents('http://tinyurl.com/api-create.php?url='.$_GET['url']);
        echo '{"status" : 0, "shortenedUrl" : "'.$shortenedUrl.'"}';
    }catch(Exception $ex){
        echo '{"status" : -1, "error" : "'.$ex->getMessage().'"}';
        $logError($ex->getMessage());
    }
    exit();
}

if(isset($_GET['op']) && $_GET['op'] == 'save'){
    header('Content-Type: application/json');
    try{
        $configFolderFull = getcwd().'/'.$configFolder;
        $reportFolderFull = getcwd().'/'.$reportFolder;
        $jsonString = file_get_contents('php://input');
        $json = json_decode($jsonString);
        if(!isset($json->uuid) || $json->uuid=='')
            throw new Exception('uuid not specified');
        if(!isset($json->trackUUID) || $json->trackUUID=='')
            throw new Exception('trackUUID not specified');
        if (!file_exists($configFolderFull))
            mkdir($configFolderFull, 0777, true);
        if (!file_exists($reportFolderFull))
            mkdir($reportFolderFull, 0777, true);
        if (!file_exists($reportFolderFull.'/'.$json->trackUUID.'.json')){
            file_put_contents($reportFolderFull.'/'.$json->trackUUID.'.json', '{"uuid" : "'.$json->trackUUID.'", "configUUID" : "'.$json->uuid.'", "time" : "'.time().'", "trackList" : []}');
        } else {
            $reportJson = json_decode(file_get_contents($reportFolderFull.'/'.$json->trackUUID.'.json'));
            if($reportJson->configUUID != $json->uuid){
                $reportJson->configUUID = $json->uuid;
                file_put_contents($reportFolderFull.'/'.$json->trackUUID.'.json', json_encode($reportJson));
            }
        }
        file_put_contents($configFolderFull.'/'.$json->uuid.'.json', $jsonString);
        echo '{"status" : 0}';
    }catch(Exception $ex){
        echo '{"status" : -1, "error" : "'.$ex->getMessage().'"}';
        $logError($ex->getMessage());
    }
    exit();
}

if(isset($_GET['op']) && $_GET['op'] == 'loadConfig'){
    header('Content-Type: application/json');
    try{
        if(!isset($_GET['id']))
            throw new Exception('id parameter required');
        $configUUID = $_GET['id'];
        if(!file_exists(getcwd().'/'.$configFolder.'/'.$configUUID.'.json'))
            throw new Exception('Invalid id '. $configUUID);
        $configString = file_get_contents(getcwd().'/'.$configFolder.'/'.$configUUID.'.json');
        echo '{"status" : 0, "config" : '.$configString.'}';
    }catch(Exception $ex){
        echo '{"status" : -1, "error" : "'.$ex->getMessage().'"}';
        $logError($ex->getMessage());
    }
    exit();
}

if(isset($_GET['op']) && $_GET['op'] == 'loadTrack'){
    header('Content-Type: application/json');
    try{
        if(!isset($_GET['id']))
            throw new Exception('id parameter required');
        $configUUID = $_GET['id'];
        if(!file_exists(getcwd().'/'.$configFolder.'/'.$configUUID.'.json'))
            throw new Exception('Invalid id '. $configUUID);
        $config = json_decode(file_get_contents(getcwd().'/'.$configFolder.'/'.$configUUID.'.json'));
        $trackUUID = $config->trackUUID;
        if(!file_exists(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json'))
            throw new Exception('Invalid track id '. $trackUUID);
        $trackString = file_get_contents(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json');
        echo '{"status" : 0, "track" : '.$trackString.'}';
    }catch(Exception $ex){
        echo '{"status" : -1, "error" : "'.$ex->getMessage().'"}';
        $logError($ex->getMessage());
    }
    exit();
}

if(isset($_GET['op']) && $_GET['op'] == 'ping'){
    header('Content-Type: application/json');
    try{
        if(!isset($_GET['id']))
            throw new Exception('id parameter required');
        if(!isset($_GET['time']))
            throw new Exception('time parameter required');
        $trackUUID = $_GET['id'];
        $localTime = $_GET['time'];
        if(!file_exists(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json'))
            throw new Exception('Invalid id '. $trackUUID);
        $fileTime = filemtime(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json');
        echo '{"status" : 0, "valid" : '.($fileTime <= $localTime?'true':'false').'}';
    }catch(Exception $ex){
        echo '{"status" : -1, "error" : "'.$ex->getMessage().'"}';
        $logError($ex->getMessage());
    }
    exit();
}

if(isset($_GET['op']) && $_GET['op'] == 'i'){
    try{
        if(!isset($_GET['tid']))
            throw new Exception('tid parameter required');
        $trackUUID = $_GET['tid'];
        if(!file_exists(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json'))
            throw new Exception('Invalid tid '. $trackUUID);
        $track = json_decode(file_get_contents(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json'));
        if(!file_exists(getcwd().'/'.$configFolder.'/'.$track->configUUID.'.json'))
            throw new Exception('Internal Error: impossible to find the configuration file associated to the tid '. $trackUUID);
        $config = json_decode(file_get_contents(getcwd().'/'.$configFolder.'/'.$track->configUUID.'.json'));
        if($config->trackingEnabled === TRUE && !isset($_COOKIE[$track->configUUID])){
            array_push($track->trackList, array(
                'time'=>date('d-m-Y H:i:s', time()), 
                'ip' => $_SERVER['REMOTE_ADDR'],
                'headers' => getallheaders()
            ));
            $track->time = time();
            file_put_contents(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json', json_encode($track));
            if(function_exists('mail') && isset($config->notificationAddress) && $config->notificationAddress!=''){
                $mailText = '<html><body><p>Your tracking image has been visualized right now by '.$_SERVER['REMOTE_ADDR'].'.</p><p>Check all the details in the <a href="'.(isset($_SERVER['HTTPS'])?'https':'http').'://'.$_SERVER['HTTP_HOST'].strtok($_SERVER['REQUEST_URI'],'?').'?op='.$dashboardPage.'&uuid='.$config->uuid.'">DASHBOARD</a></p></body></html>';
                mail($config->notificationAddress, '[Tracking Live Report] '.$config->mailId, wordwrap($mailText, 70, "\r\n"), "MIME-Version: 1.0\r\nContent-type:text/html;charset=UTF-8\r\n");
            }
        }  
        $headerAddedList = array();
        foreach($config->trackingImageCustomHeaderList as $header){
            $key = explode(':', $header)[0];
            header($header, !in_array($key, $headerAddedList, TRUE), $config->trackingImageStatusCode);
            $headerAddedList[] = $key;
        }
        http_response_code($config->trackingImageStatusCode);
        if(isset($config->trackingImage) && $config->trackingImage!='')
            echo file_get_contents($config->trackingImage);
    }catch(Exception $ex){
        $logError($ex->getMessage());
        http_response_code(400);
    }
    exit();
}

if(isset($_GET['op']) && $_GET['op'] == 'l'){
    try{
        if(!isset($_GET['tid']))
            throw new Exception('tid parameter required');
        if(!isset($_GET['lid']))
            throw new Exception('lid parameter required');
        $trackUUID = $_GET['tid'];
        $linkUUID = $_GET['lid'];
        if(!file_exists(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json'))
            throw new Exception('Invalid tid '. $trackUUID);
        $track = json_decode(file_get_contents(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json'));
        if(!file_exists(getcwd().'/'.$configFolder.'/'.$track->configUUID.'.json'))
            throw new Exception('Internal Error: impossible to find the configuration file associated to the tid '. $trackUUID);
        $config = json_decode(file_get_contents(getcwd().'/'.$configFolder.'/'.$track->configUUID.'.json'));
        if($config->trackingEnabled === TRUE && !isset($_COOKIE[$track->configUUID])){
            array_push($track->trackList, array(
                'time'=>date('d-m-Y H:i:s', time()),
                'ip' => $_SERVER['REMOTE_ADDR'],
                'headers' => getallheaders()
            ));
            $track->time = time();
            file_put_contents(getcwd().'/'.$reportFolder.'/'.$trackUUID.'.json', json_encode($track));
            if(function_exists('mail') && isset($config->notificationAddress) && $config->notificationAddress!=''){
                $mailText = '<html><body><p>Your tracking link has been clicked right now by '.$_SERVER['REMOTE_ADDR'].'.</p><p>Check all the details in the <a href="'.(isset($_SERVER['HTTPS'])?'https':'http').'://'.$_SERVER['HTTP_HOST'].strtok($_SERVER['REQUEST_URI'],'?').'?op='.$dashboardPage.'&uuid='.$config->uuid.'">DASHBOARD</a></p></body></html>';
                mail($config->notificationAddress, '[Tracking Live Report] '.$config->mailId, wordwrap($mailText, 70, "\r\n"), "MIME-Version: 1.0\r\nContent-type:text/html;charset=UTF-8\r\n");
            }
        }
        if(!isset($config->trackingLinks->$linkUUID))
            throw new Exception('Impossible to find the link '.$linkUUID);
        $redirectToUrl = $config->trackingLinks->$linkUUID->original;
        if(isset($redirectToUrl) && $redirectToUrl!='')
            header('Location: '.$redirectToUrl);
        else
            http_response_code(404);
    }catch(Exception $ex){
        $logError($ex->getMessage());
        http_response_code(400);
    }
    exit();
}

header('Content-Type: application/json');
echo '{"status" : -1, "error" : "op parameter not valid"}';
$logError('op parameter not valid');
exit();
?>